apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tinkerbell
  namespace: flux-system
spec:
  interval: 1m
  url: "https://github.com/tinkerbell/charts/tinkerbell/stack"
  ref:
    branch: main
