---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tinkerbell
  namespace: flux-system
spec:
  targetNamespace: tink-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/fluxcd/repositories/clusters/dev-cluster/apps/tink-system/tinkerbell/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m